# Copy/paste friendly list of sources (you can edit anytime)

# --- Google (official)
- https://developers.google.com/search/blog/feed.xml
- https://developers.google.com/search/news
- https://status.search.google.com/
- https://developers.google.com/search/podcasts/search-off-the-record

# --- Industry news & analysis
- https://searchengineland.com/feed
- https://rss.searchenginejournal.com/
- https://www.seroundtable.com/index.xml
- https://ahrefs.com/blog/feed/
- https://moz.com/blog/feed
- https://www.semrush.com/blog/feed/
- https://www.sistrix.com/feed/

# --- Analysts / influencers
- https://www.mariehaynes.com/feed/
- https://brodieclark.com/blog/
- https://www.amsive.com/insights/category/seo/
- https://www.gsqi.com/marketing-blog/
- https://sparktoro.com/blog/feed/

# --- Volatility (signals)
- https://www.semrush.com/sensor/
- https://algoroo.com/
