name: Run SEO scraper

on:
  schedule:
    - cron: '0 6 */3 * *'   # every 3 days at 06:00 UTC
  workflow_dispatch: {}

# Allow this workflow to push the updated news.json back to the repo
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml beautifulsoup4

      - name: Run scraper
        run: |
          python scraper/scraper.py

      - name: Commit updated news.json (only if changed)
        run: |
          git config user.name "seo-news-bot"
          git config user.email "bot@example.com"
          git add data/news.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update news feed"
            git pull --rebase
            git push
          fi

